FaucheurBundle\Entity\RoleAction:
    type: entity
    table: role_action
    id: {  }
    fields:
        nomRole:
            type: string
            nullable: true
            length: 150
            options:
                fixed: false
            column: nom_role
    oneToOne:
        idRole:
            targetEntity: ParticipeAction
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_role:
                    referencedColumnName: id_role
            orphanRemoval: false
    lifecycleCallbacks: {  }
